[server]
enableXsrfProtection = true
enableCORS = false

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[logger]
level = "info"

[browser]
gatherUsageStats = false

[deprecation]
showfileUploaderEncoding = false

[runner]
fastReruns = true